/**
 * This script loads a clippings.txt file generated by Kindle, uses kindle-clippings-parser to parse it, and then formats the output to display each title with its highlights */
var fs = require('fs');
var path = require('path');

var parse = require('../').parse;

var fileContents = fs.readFileSync(path.join(__dirname, './test-clippings.txt'), 'utf-8');

var parsed = parse(fileContents);

parsed.forEach(function(item) {
	console.log(item.title);
	
	var underline = '';
	for(i = 0; i < item.title.length; i++) {
		underline += '=';
	}
	console.log(underline);

	item.highlights.forEach(function(h) {
		console.log('* ' + h.text);
	});

	console.log('\n');

});
